package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/markedo-org/ledger/internal/types"
)

func Markdown(l types.Ledger, tasks []types.Task, host string) string {
	src := fmt.Sprintf("http://%s/%s/%s", host, l.OwnerSlug, l.Slug)
	var b strings.Builder
	b.WriteString("<!-- generated by task-ledger; do not edit. Source: ")
	b.WriteString(src)
	b.WriteString(" -->\n")
	b.WriteString("# Task Ledger\n\n")
	b.WriteString("> Generated snapshot of **")
	b.WriteString(l.OwnerSlug)
	b.WriteString("/")
	b.WriteString(l.Slug)
	b.WriteString("**. The live ledger is the write path. Do not edit this file.\n\n")

	order := []types.Phase{types.PhaseNOW, types.PhaseNEXT, types.PhaseLATER, types.PhaseGATED, types.PhasePARKED, types.PhaseDONE}
	by := map[types.Phase][]types.Task{}
	for _, t := range tasks {
		by[t.Phase] = append(by[t.Phase], t)
	}
	now := time.Now().UTC()
	for _, p := range order {
		b.WriteString("## ")
		b.WriteString(string(p))
		b.WriteString("\n\n")
		list := by[p]
		if len(list) == 0 {
			b.WriteString("*(empty)*\n\n")
			continue
		}
		for _, t := range list {
			fmt.Fprintf(&b, "- [ ] **%s** %s\n", t.Handle, t.Title)
			if p == types.PhaseDONE && t.Evidence != "" {
				day := ""
				if t.ClosedAt != nil {
					day = t.ClosedAt.Format("2006-01-02")
				}
				fmt.Fprintf(&b, "  ↳ done %s · evidence: %s\n", day, t.Evidence)
			} else {
				fmt.Fprintf(&b, "  ↳ since %s · pushed %d · size %s", t.Since.Format("2006-01-02"), t.Pushed, dashSize(t.Size))
				if t.Ref != "" {
					fmt.Fprintf(&b, " · ref `%s`", t.Ref)
				}
				b.WriteString("\n")
			}
			if t.ClaimedBy != "" && t.ClaimedUntil != nil && t.ClaimedUntil.After(now) {
				fmt.Fprintf(&b, "  held by %s until %s\n", t.ClaimedBy, t.ClaimedUntil.UTC().Format(time.RFC3339))
			}
			for _, c := range t.Checks {
				mark := " "
				if c.Done {
					mark = "x"
				}
				fmt.Fprintf(&b, "  - [%s] %s\n", mark, c.Body)
			}
			b.WriteString("\n")
		}
	}
	return b.String()
}

func dashSize(s types.Size) string {
	if s == "" {
		return "-"
	}
	return string(s)
}
